### ISSUE TITLE
Twitter media players are hidden

### ISSUE THREAD

**Issue by oscarmarcelo** [apankrat/internet-improvement-project#2]
The following line is also matching Twitter's media players:

https://github.com/apankrat/internet-improvement-project/blob/bd24181e595f5316fd913229e40c7814c63b56fa/twitter/declutterTwitter.user.js#L50

**Test cases**:
GIF: https://twitter.com/nixcraft/status/842254695892623360
Video: https://twitter.com/NickTyson/status/1251029259167993856

**Comment by apankrat** [comment]
Are you sure that's the cause? In the GIF test case I see an empty frame even with GM completely off. Ditto in video.

**But** I don't think embedded videos on Twitter ever worked reliably for me to begin with.

**Comment by apankrat** [comment]
Ah, damn, sorry. You are absolutely right! I had this line commented out in my own copy of the script, I just forgot to push it out to github :-/

**Comment by oscarmarcelo** [comment]
No problem. Thanks for the quick fix! 👍

(I've been a fan of your work for quite some time, btw!)
